name: Lint

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint using GitHub SuperLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv lock -r | pip install -r
      - name: Lint Code Base
        uses: docker://github/super-linter:v3.2.0
