name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint using ruff and black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: '.python-version'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e . --group dev
      - name: Run ruff
        run: ruff check .
      - name: Run black
        run: black --check .
